base:
  project: iThome2022
  experiment: run_epoch100_with_L2
  
make_dataset:
  dataset_from: 'chestmnist'
  tmp_folder: 'data'
  save_folder: 'data'
  img_subfilename: 'png'
  dataset_file: 'data/dataset.csv'

preprocess:
  dataset_file: 'data/chestmnist.npz'
  input_size: [28, 28]
  input_channels: 3
  imagenet_statistics: False

train:
  backbone: 'efficientnet-b0'
  pretrain: True
  splits : ['TRAIN', 'VALIDATION']
  cached_train_part: True
  shuffle:
    TRAIN: True
    VALIDATION: False
  data_aug:
    use: True
    prob: 0.25
  dataset_fun:
    name: 'Dataset'
    args: {}
  data_loader:
    num_workers: 16
    prefetch_factor: 4
  batch_size: 128
  max_epochs: 100
  steps_in_epoch: null
  trainer:
    accelerator: 'cuda'
    devices: 1
    profiler: 'simple'
    log_every_n_steps: 1
    benchmark: True
    precision: 32
  loss_function: 'BCEWithLogitsLoss'
  weight_decay:
    p: 2
    lambda: 0.01
  label_smooth: 0
  optimizer: 
    name: 'Adam'
    learning_rate: 0.001
    weight_decay: 0
    warmup_epochs: 5
    scheduler: 
      name: 'CosineAnnealingLR' 
      params: 
        verbose: true
        T_max: 25
        eta_min: 0.00003
        last_epoch: -1
  weights_folder: 'artefacts/weights'
  
evaluate:
  batch_size: 512
  weights_path: 'artefacts/weights/run_epoch100_with_pretrained/epoch_30_val_loss_0.16_val_acc_0.95_val_auroc_0.76.ckpt'
  tester:
    accelerator: 'cuda'
    devices: 1
    precision: 32
  