base:
  project: iThome2022
  experiment: run_with_16workers_4pf_with_cached
  
make_dataset:
  dataset_from: 'chestmnist'
  tmp_folder: '/tmp'
  save_folder: 'data'
  img_subfilename: 'png'
  dataset_file: 'data/dataset.csv'

train:
  gpus: 
  backbone: 'efficientnet-b0'
  splits : ['TRAIN', 'VALIDATION']
  cached_train_part: True
  shuffle:
    TRAIN: True
    VALIDATION: False
  dataset_fun:
    name: CacheDataset
    args:
      num_workers: 16
  batch_size: 128
  max_epochs: 5
  steps_in_epoch: 50
  data_loader:
    num_workers: 16
    prefetch_factor: 4

  loss_function: 'BCEWithLogitsLoss'
  optimizer: 'Adam'
  learning_rate: 0.0001
  weights_folder: 'artefacts/weights'