base:
  project: iThome2022
  
make_dataset:
  dataset_from: 'chestmnist'
  tmp_folder: '/tmp'
  save_folder: 'data'
  img_subfilename: 'png'
  dataset_file: 'data/dataset.csv'

train:
  gpus: 
  backbone: 'efficientnet-b0'
  batch_size: 256
  max_epochs: 10
  steps_in_epoch: null
  data_loader:
    num_workers: 8
    prefetch_factor: 16
  shuffle:
    TRAIN: True
    VALIDATION: False
    TEST: False
  loss_function: 'BCEWithLogitsLoss'
  optimizer: 'Adam'
  learning_rate: 0.01
  weights_folder: 'artefacts/weights'